# python -m src.trainers.run_parameter_search_optuna_local --config configs/gin_gru_2_points.yaml --n-trials 50 --epochs 50
device: cpu # if null, it automatically sets the available device. (cuda | mps | cpu)
            # it is often better to use cpu due to recurrent unit.
edge:
  is_mi_based: True # if 0, it generates fully connected edge index.
  n_neighbors: 3 # NOTE: cv result of n_neighbors: 3
  top_k: 6
  threshold: 0.01
  pruning_ratio: 0.5
  return_edge_attr: False # CAUTION: potential error when set to True
  mi_cached: True
  cache_path: None

model:
  name: gin_gru
  params:
    embedding_dim: 32
    gin_hidden_channel: 32
    train_eps: True
    gin_layers: 2
    gru_hidden_channel: 64
    dropout_p: 0.2

train:
  batch_size: 32
  learning_rate: 0.001 # optimizer learning rate
  epochs: 20
  seed: 1 
  binary: True
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  num_workers: 3
  lr_scheduler_patience: 10
  early_stopping_patience: 15
  decision_threshold: 0.5
  cv: False
  n_folds: 5