from src.models.discharge_predictor.model import MultiTaskDischargePredictor
from src.models.discharge_predictor.loss import (
    MultiTaskCategoricalLoss,
    multiclass_focal_loss,
)
from src.models.discharge_predictor.metrics import compute_discharge_metrics, compute_ordinal_metrics
from src.models.discharge_predictor.los_ordinal_model import LOSOrdinalPredictor
from src.models.discharge_predictor.los_coarse_model import LOSCoarsePredictor
from src.models.discharge_predictor.conditioners import (
    ExpectedCategoricalEmbedding,
    MultiHeadExpectedEmbedding,
    mix_condition_distributions,
    one_hot_distribution,
    parse_bool_flag,
    resolve_joint_heads,
)
from src.models.discharge_predictor.joint_consistent_predictor import (
    FixedOneHotBatchEncoder,
    JointConsistentPredictor,
    JointPredictorOutput,
)
from src.models.discharge_predictor.joint_consistency_loss import (
    JointConsistencyLoss,
    compute_joint_consistency_penalty,
)
from src.models.discharge_predictor.soft_joint_drift_loss import SoftJointDriftLoss
from src.models.discharge_predictor.risk_heads import (
    LEGACY_TOP3_HEADS,
    RISK_HEAD_SETS,
    available_risk_head_sets,
    get_named_risk_head_set,
    resolve_risk_head_selection,
)
from src.models.discharge_predictor.joint_generative_predictor import (
    AdmissionGraphEncoder,
    FuturePosteriorEncoder,
    FuturePrior,
    JointFutureDecoder,
    JointGenerativeLoss,
    JointGenerativePredictor,
    JointGenerativePredictorOutput,
    diagonal_gaussian_kl,
    kl_beta_for_epoch,
)
from src.models.discharge_predictor.los_utils import (
    LOS_COARSE_BINS,
    LOS_COARSE_BIN_REPRESENTATIVES,
    LOS_COARSE_BREAKDOWN_BINS,
    LOS_COARSE_BREAKDOWN_BIN_REPRESENTATIVES,
    LosBinningMetadata,
    expand_coarse_distribution_to_raw_los,
    get_los_coarse_bins,
    get_los_coarse_bin_representatives,
    get_los_coarse_class_labels,
    get_los_coarse_class_names,
    get_los_coarse_num_classes,
    infer_los_coarse_breakdown_from_cfg,
    infer_los_target_from_cfg,
    los_binning_metadata_dict,
    map_coarse_array_to_raw_los,
    map_coarse_bin_to_raw_los,
    map_los_array_to_coarse_bins,
    map_los_to_coarse_bin,
)
from src.models.discharge_predictor.ordinal_loss import (
    OrdinalBCELoss,
    compute_ordinal_constraint_metrics,
    fit_ordinal_thresholds,
    score_ordinal_objective,
)

__all__ = [
    "MultiTaskDischargePredictor",
    "MultiTaskCategoricalLoss",
    "multiclass_focal_loss",
    "compute_discharge_metrics",
    "compute_ordinal_metrics",
    "LOSOrdinalPredictor",
    "LOSCoarsePredictor",
    "ExpectedCategoricalEmbedding",
    "MultiHeadExpectedEmbedding",
    "mix_condition_distributions",
    "one_hot_distribution",
    "parse_bool_flag",
    "resolve_joint_heads",
    "FixedOneHotBatchEncoder",
    "JointConsistentPredictor",
    "JointPredictorOutput",
    "JointConsistencyLoss",
    "compute_joint_consistency_penalty",
    "SoftJointDriftLoss",
    "LEGACY_TOP3_HEADS",
    "RISK_HEAD_SETS",
    "available_risk_head_sets",
    "get_named_risk_head_set",
    "resolve_risk_head_selection",
    "AdmissionGraphEncoder",
    "FuturePosteriorEncoder",
    "FuturePrior",
    "JointFutureDecoder",
    "JointGenerativeLoss",
    "JointGenerativePredictor",
    "JointGenerativePredictorOutput",
    "diagonal_gaussian_kl",
    "kl_beta_for_epoch",
    "LOS_COARSE_BINS",
    "LOS_COARSE_BIN_REPRESENTATIVES",
    "LOS_COARSE_BREAKDOWN_BINS",
    "LOS_COARSE_BREAKDOWN_BIN_REPRESENTATIVES",
    "LosBinningMetadata",
    "expand_coarse_distribution_to_raw_los",
    "get_los_coarse_bins",
    "get_los_coarse_bin_representatives",
    "get_los_coarse_class_labels",
    "get_los_coarse_class_names",
    "get_los_coarse_num_classes",
    "infer_los_coarse_breakdown_from_cfg",
    "infer_los_target_from_cfg",
    "los_binning_metadata_dict",
    "map_coarse_array_to_raw_los",
    "map_coarse_bin_to_raw_los",
    "map_los_array_to_coarse_bins",
    "map_los_to_coarse_bin",
    "OrdinalBCELoss",
    "compute_ordinal_constraint_metrics",
    "fit_ordinal_thresholds",
    "score_ordinal_objective",
]
